polybar: add gaurd for ifconfig.me

diff --git a/polybar/scripts/info-pingrtt b/polybar/scripts/info-pingrtt
--- a/polybar/scripts/info-pingrtt
+++ b/polybar/scripts/info-pingrtt
@@ -1,8 +1,10 @@
 #!/bin/sh
 
 HOST=$(curl ifconfig.me 2> /dev/null)
-#HOST=$(ip route get 1.1.1.1 | grep -oP 'src \K\S+')
-#HOST=google.com
+if [ $? -ne 0 ]; then
+  echo "# ifconfig.me failed"
+  exit 1
+fi
 
 if ! ping=$(ping -n -c 1 -W 1 $HOST); then
     echo "# ping failed"
