polybar: make ping rtt tailing
This limits resources and removes the host lookup at every run.

diff --git a/polybar/scripts/info-pingrtt b/polybar/scripts/info-pingrtt
--- a/polybar/scripts/info-pingrtt
+++ b/polybar/scripts/info-pingrtt
@@ -1,23 +1,29 @@
-#!/bin/sh
+#!/bin/zsh
 
-HOST=$(curl ifconfig.me 2> /dev/null)
-if [ $? -ne 0 ]; then
-  echo "# ifconfig.me failed"
-  exit 1
-fi
+while true;
+do
+	HOST=$(curl ifconfig.me 2> /dev/null)
+	if [ $? -ne 0 ]; then
+		echo "# ifconfig.me failed"
+		sleep 1
+		continue
+	fi
 
-if ! ping=$(ping -n -c 1 -W 1 $HOST); then
-    echo "# ping failed"
-else
-    rtt=$(echo "$ping" | sed -rn 's/.*time=([0-9]{1,})\.?[0-9]{0,} ms.*/\1/p')
+	if ! ping=$(ping -n -c 1 -W 1 $HOST); then
+		echo "# ping failed"
+		sleep 1
+		continue
+	fi
 
-    if [ "$rtt" -lt 50 ]; then
-        icon="%{F#3cb703}#%{F-}"
-    elif [ "$rtt" -lt 150 ]; then
-        icon="%{F#f9dd04}#%{F-}"
-    else
-        icon="%{F#d60606}#%{F-}"
-    fi
+	rtt=$(echo "$ping" | sed -rn 's/.*time=([0-9]{1,})\.?[0-9]{0,} ms.*/\1/p')
 
-    echo " $rtt ms"
-fi
+	if [ "$rtt" -lt 11 ]; then
+		# orange
+		echo " ${rtt} ms"
+	elif [ "$rtt" -lt 51 ]; then
+		echo "%{F#f9dd04} ${rtt} ms%{F-}"
+	else
+		echo "%{F#d60606} ${rtt} ms%{F-}"
+	fi
+	sleep 1
+done
